### ISSUE TITLE
Chase Bliss - Bliss Factory Support

### ISSUE THREAD

**Issue by averageram** [ElliotGarbus/ChaseBlissEditor#2]
I own a Chase Bliss - Bliss Factory and would love to use this editor.  How can I contribute to enable support for this pedal?

Cheers,
Rick

**Comment by ElliotGarbus** [comment]
Hi Rick,
If you are a python developer and you are asking how to do you fork and contribute to the code... let me know.  It would not be hard to add the Bliss Factory. 

If you are new to using the editor I would encourage you to try out the editor.  If you only have the Bliss Factory, You could select the condor, while the controls will not be labeled correctly you  will get to see how all of the features of the editor work with the Bliss Factory.  Just focus on the on screen knob positions. 

If you find there is enough value in the editor and it is working for you - let me know.  I can add the Bliss Factory when I have time.

The features of the editor are a limited due to the midi implementation of the Chase Bliss pedals - but still effective for many users.

**Comment by averageram** [comment]
Unfortunately I'm not a python dev.  I'll try things out with the Condor settings and report back.  Thank you.!
